inhibit_all_warnings!
install! 'cocoapods', :disable_input_output_paths => true
target 'iosApp' do
  use_frameworks!
  platform :ios, '15.0'
  pod 'MultiPlatformLibrary', :path => '../shared'
  pod 'mokoMvvmFlowSwiftUI', :podspec => 'https://raw.githubusercontent.com/icerockdev/moko-mvvm/release/0.16.1/mokoMvvmFlowSwiftUI.podspec'
end